/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'piandv' at '7/29/15 10:25 AM' with Gradle 2.5-rc-2
 *
 * @author piandv, @date 7/29/15 10:25 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
